### ISSUE TITLE
#01 CSSの基本セレクターを学んでいこう

### ISSUE THREAD

**Issue by Shirahamah** [Shirahamah/dotinstall_basic_css_selectors#1]
### URL
[#01 CSSの基本セレクターを学んでいこう | 詳解CSS セレクター編 - プログラミングならドットインストール](https://dotinstall.com/lessons/basic_css_selectors/52701)

### 講座内容
- CSS記法の復習
- 基本セレクターの種類

### 成果物
- なし
セレクターの種類をスライドで説明

### コメント
- 要素型、class、id、属性、全称の5種類のセレクターがあることがわかった。

**Comment by Shirahamah** [comment]
完了しました。

**Comment by sugasaki-atsushi** [comment]
@Shirahamah 
結果を見るURLが抜けてるね。

**Comment by sugasaki-atsushi** [comment]
成果物なしだったか。すまん
